### ISSUE TITLE
Can't install on ubuntu

### ISSUE THREAD

**Issue by damoebius** [clemos/npm-haxe#4]
I try "npm install clemos/npm-haxe" and "sudo npm install clemos/npm-haxe" but i got an error message 
https://pbs.twimg.com/media/CcE4EQ_XEAA09mp.jpg:large

ubuntu 14.04
npm 1.3.10
nodejs 0.10.25

**Comment by clemos** [comment]
Thanks for your report.
Can you please send the complete npm-debug.log file ?

**Comment by clemos** [comment]
I just set Travis CI to test against node 0.10.
I had to do a minor fix for the `npm test` command to make it work on 0.10, 
but `npm install` seemed ok.
Versions are not quite the same as yours, though : https://travis-ci.org/clemos/npm-haxe/jobs/114532475#L146
Anyway, let me know when you have any news ;)

**Comment by damoebius** [comment]
OK i get it, the node command wasn't available on my ubuntu, but i used the "nodejs" command instead

I resolve it with that : http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu

We included a workaround in the main haxe module here : https://github.com/damoebius/haxe-npm/blob/master/bin/haxe

**Comment by clemos** [comment]
Ok 
I'll add a note in the README with this command `sudo apt-get install nodejs-legacy`
I prefer to drop the hack for now.
Thanks for your investigation :)
